[package]
name = "advent_template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
regex = "1.5"
anyhow = "1"
log = "0.4"
tap = "1.0"
itertools = "0.10"
nom = "7.1"
pathfinding = "3.0"